# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master
strategy:
  matrix:
    win-chrome:
      imageName: windows-2019
      browser: chrome
  
pool:
  vmImage: $(imageName)


variables: 
  buildConfiguration: 'Release'
  SELENIUM_BROWSER: $(browser)

steps:
  - task: DotNetCoreCLI@2
    displayName: dotnet test
    inputs:
      command: test
      projects: $(Build.SourcesDirectory)/csharp-selenium-webdriver-sample/**/*.csproj
      publishTestResults: true
      testRunTitle: "dotnet test ($(imageName) $(browser))"
      # We use this EXTRA_DOTNET_TEST_ARGUMENTS variable in the sample's CI/PR builds so the "success" examples can --filter
      # out the tests that intentionally fail for example purposes. You probably don't need this in a real project.
      arguments: $(EXTRA_DOTNET_TEST_ARGUMENTS)

     
